/*
 *
 * 
 * 
 */

import javax.swing.JOptionPane;
import gauss.GaussCalculator;

/**
 *
 * @author
 */
public class GUIGaussMethod extends javax.swing.JFrame {

    GaussCalculator calculator;
    GUI gui;
    private double[][] matrix = new double[5][6];
    
    /**
     * Creates new form
     */
    public GUIGaussMethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                                   
                                   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        calculate_button = new javax.swing.JButton();
        clean_button = new javax.swing.JButton();
        principal_button = new javax.swing.JButton();
        MatrixPane = new javax.swing.JPanel();
        ValuesPane = new javax.swing.JPanel();
        a01 = new javax.swing.JTextField();
        a02 = new javax.swing.JTextField();
        a03 = new javax.swing.JTextField();
        a04 = new javax.swing.JTextField();
        a05 = new javax.swing.JTextField();
        a15 = new javax.swing.JTextField();
        a14 = new javax.swing.JTextField();
        a13 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        a22 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a21 = new javax.swing.JTextField();
        a23 = new javax.swing.JTextField();
        a24 = new javax.swing.JTextField();
        a25 = new javax.swing.JTextField();
        a35 = new javax.swing.JTextField();
        a34 = new javax.swing.JTextField();
        a33 = new javax.swing.JTextField();
        a32 = new javax.swing.JTextField();
        a31 = new javax.swing.JTextField();
        a41 = new javax.swing.JTextField();
        a42 = new javax.swing.JTextField();
        a43 = new javax.swing.JTextField();
        a44 = new javax.swing.JTextField();
        a45 = new javax.swing.JTextField();
        ResultsPane = new javax.swing.JPanel();
        a06 = new javax.swing.JTextField();
        a16 = new javax.swing.JTextField();
        a26 = new javax.swing.JTextField();
        a36 = new javax.swing.JTextField();
        a46 = new javax.swing.JTextField();
        LabelsPane = new javax.swing.JPanel();
        label_v = new javax.swing.JLabel();
        labe_w = new javax.swing.JLabel();
        label_x = new javax.swing.JLabel();
        label_y = new javax.swing.JLabel();
        label_z = new javax.swing.JLabel();
        label_r = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultArea.setEditable(false);
        resultArea.setColumns(20);
        resultArea.setRows(5);
        scrollPane.setViewportView(resultArea);

        calculate_button.setText("Calcular");
        calculate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_buttonActionPerformed(evt);
            }
        });

        clean_button.setText("Limpiar");
        clean_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_buttonActionPerformed(evt);
            }
        });

        principal_button.setText("Principal");
        principal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principal_buttonActionPerformed(evt);
            }
        });

        a01.setText("1");
        a01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a01ActionPerformed(evt);
            }
        });

        a02.setText("2");

        a03.setText("3");

        a04.setText("0");
        a04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a04ActionPerformed(evt);
            }
        });

        a05.setText("0");

        a15.setText("0");

        a14.setText("0");

        a13.setText("6");

        a12.setText("5");

        a22.setText("8");

        a11.setText("4");

        a21.setText("7");

        a23.setText("1");

        a24.setText("0");

        a25.setText("0");

        a35.setText("0");

        a34.setText("0");

        a33.setText("0");

        a32.setText("0");

        a31.setText("0");

        a41.setText("0");

        a42.setText("0");

        a43.setText("0");

        a44.setText("0");

        a45.setText("0");

        javax.swing.GroupLayout ValuesPaneLayout = new javax.swing.GroupLayout(ValuesPane);
        ValuesPane.setLayout(ValuesPaneLayout);
        ValuesPaneLayout.setHorizontalGroup(
            ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValuesPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a41, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ValuesPaneLayout.createSequentialGroup()
                        .addComponent(a32, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a33, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a34, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a35, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ValuesPaneLayout.createSequentialGroup()
                        .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a03, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a04, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a05, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ValuesPaneLayout.createSequentialGroup()
                        .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ValuesPaneLayout.createSequentialGroup()
                        .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ValuesPaneLayout.createSequentialGroup()
                        .addComponent(a42, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a43, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a44, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a45, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ValuesPaneLayout.setVerticalGroup(
            ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValuesPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a03, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a04, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a05, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a34, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValuesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a41, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a42, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a43, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a44, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a45, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        a06.setText("10");

        a16.setText("20");

        a26.setText("30");

        a36.setText("0");

        a46.setText("0");

        javax.swing.GroupLayout ResultsPaneLayout = new javax.swing.GroupLayout(ResultsPane);
        ResultsPane.setLayout(ResultsPaneLayout);
        ResultsPaneLayout.setHorizontalGroup(
            ResultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a46, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a36, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a06, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ResultsPaneLayout.setVerticalGroup(
            ResultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a06, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a36, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a46, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label_v.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_v.setText("V");

        labe_w.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labe_w.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labe_w.setText("W");

        label_x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_x.setText("X");

        label_y.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_y.setText("Y");

        label_z.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_z.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_z.setText("Z");

        label_r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_r.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_r.setText("R");

        javax.swing.GroupLayout LabelsPaneLayout = new javax.swing.GroupLayout(LabelsPane);
        LabelsPane.setLayout(LabelsPaneLayout);
        LabelsPaneLayout.setHorizontalGroup(
            LabelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_v, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labe_w, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_x, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_y, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_z, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_r, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        LabelsPaneLayout.setVerticalGroup(
            LabelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabelsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_v)
                    .addComponent(labe_w)
                    .addComponent(label_x)
                    .addComponent(label_y)
                    .addComponent(label_z)
                    .addComponent(label_r))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MatrixPaneLayout = new javax.swing.GroupLayout(MatrixPane);
        MatrixPane.setLayout(MatrixPaneLayout);
        MatrixPaneLayout.setHorizontalGroup(
            MatrixPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MatrixPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MatrixPaneLayout.createSequentialGroup()
                        .addComponent(ValuesPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MatrixPaneLayout.setVerticalGroup(
            MatrixPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ValuesPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 117, Short.MAX_VALUE)
                        .addComponent(MatrixPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(principal_button))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(calculate_button, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(clean_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MatrixPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(principal_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculate_button)
                        .addGap(18, 18, 18)
                        .addComponent(clean_button)
                        .addGap(13, 13, 13)))
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void calculate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_buttonActionPerformed
        try {
            int size = 2;
            
            for (int i = 0; i < 5; i++) { // Reset matrix to avoid errors
                for (int n = 0; n < 6; n++) {
                    matrix[i][n] = 0;
                }
            }
            
            setMatrix();

            // This define the matrix size, testing that if a row or column is of 0, then the size reduces
            if (matrix[4][0] != 0 || matrix[4][1] != 0 || matrix[4][2] != 0 || matrix[4][3] != 0 || matrix[4][4] != 0 || matrix[4][5] != 0) {
                size = 5;
            } else if (matrix[3][0] != 0 || matrix[3][1] != 0 || matrix[3][2] != 0 || matrix[3][3] != 0 || matrix[3][4] != 0 || matrix[3][5] != 0) {
                size = 4;
            } else if (matrix[2][0] != 0 || matrix[2][1] != 0 || matrix[2][2] != 0 || matrix[2][3] != 0 || matrix[2][4] != 0 || matrix[2][5] != 0) {
                size = 3;
            }
            
            calculator = new GaussCalculator(size, matrix, resultArea);
            
            calculator.calculateValues();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor llena todos los campos correctamente");
        }

    }//GEN-LAST:event_calculate_buttonActionPerformed

    public void setMatrix(){
        resultArea.setText("");// Clean up Text Area (if it was already used)
        
        // Add values to matrix
        matrix[0][0] = Double.parseDouble(a01.getText());
        matrix[0][1] = Double.parseDouble(a02.getText());
        matrix[0][2] = Double.parseDouble(a03.getText());
        matrix[0][3] = Double.parseDouble(a04.getText());
        matrix[0][4] = Double.parseDouble(a05.getText());
        matrix[0][5] = Double.parseDouble(a06.getText());
        matrix[1][0] = Double.parseDouble(a11.getText());
        matrix[1][1] = Double.parseDouble(a12.getText());
        matrix[1][2] = Double.parseDouble(a13.getText());
        matrix[1][3] = Double.parseDouble(a14.getText());
        matrix[1][4] = Double.parseDouble(a15.getText());
        matrix[1][5] = Double.parseDouble(a16.getText());
        matrix[2][0] = Double.parseDouble(a21.getText());
        matrix[2][1] = Double.parseDouble(a22.getText());
        matrix[2][2] = Double.parseDouble(a23.getText());
        matrix[2][3] = Double.parseDouble(a24.getText());
        matrix[2][4] = Double.parseDouble(a25.getText());
        matrix[2][5] = Double.parseDouble(a26.getText());
        matrix[3][0] = Double.parseDouble(a31.getText());
        matrix[3][1] = Double.parseDouble(a32.getText());
        matrix[3][2] = Double.parseDouble(a33.getText());
        matrix[3][3] = Double.parseDouble(a34.getText());
        matrix[3][4] = Double.parseDouble(a35.getText());
        matrix[3][5] = Double.parseDouble(a36.getText());
        matrix[4][0] = Double.parseDouble(a41.getText());
        matrix[4][1] = Double.parseDouble(a42.getText());
        matrix[4][2] = Double.parseDouble(a43.getText());
        matrix[4][3] = Double.parseDouble(a44.getText());
        matrix[4][4] = Double.parseDouble(a45.getText());
        matrix[4][5] = Double.parseDouble(a46.getText());
    }
    private void a01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a01ActionPerformed

    private void a04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a04ActionPerformed

    private void clean_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_buttonActionPerformed
        a01.setText(""+0);
        a02.setText(""+0);
        a03.setText(""+0);
        a04.setText(""+0);
        a05.setText(""+0);
        a06.setText(""+0);
        a11.setText(""+0);
        a12.setText(""+0);
        a13.setText(""+0);
        a14.setText(""+0);
        a15.setText(""+0);
        a16.setText(""+0);
        a21.setText(""+0);
        a22.setText(""+0);
        a23.setText(""+0);
        a24.setText(""+0);
        a25.setText(""+0);
        a26.setText(""+0);
        a31.setText(""+0);
        a32.setText(""+0);
        a33.setText(""+0);
        a34.setText(""+0);
        a35.setText(""+0);
        a36.setText(""+0);
        a41.setText(""+0);
        a42.setText(""+0);
        a43.setText(""+0);
        a44.setText(""+0);
        a45.setText(""+0);
        a46.setText(""+0);
        resultArea.setText("");
    }//GEN-LAST:event_clean_buttonActionPerformed

    private void principal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principal_buttonActionPerformed
        // TODO add your handling code here:
        gui = new GUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_principal_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LabelsPane;
    private javax.swing.JPanel MatrixPane;
    private javax.swing.JPanel ResultsPane;
    private javax.swing.JPanel ValuesPane;
    private javax.swing.JTextField a01;
    private javax.swing.JTextField a02;
    private javax.swing.JTextField a03;
    private javax.swing.JTextField a04;
    private javax.swing.JTextField a05;
    private javax.swing.JTextField a06;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a14;
    private javax.swing.JTextField a15;
    private javax.swing.JTextField a16;
    private javax.swing.JTextField a21;
    private javax.swing.JTextField a22;
    private javax.swing.JTextField a23;
    private javax.swing.JTextField a24;
    private javax.swing.JTextField a25;
    private javax.swing.JTextField a26;
    private javax.swing.JTextField a31;
    private javax.swing.JTextField a32;
    private javax.swing.JTextField a33;
    private javax.swing.JTextField a34;
    private javax.swing.JTextField a35;
    private javax.swing.JTextField a36;
    private javax.swing.JTextField a41;
    private javax.swing.JTextField a42;
    private javax.swing.JTextField a43;
    private javax.swing.JTextField a44;
    private javax.swing.JTextField a45;
    private javax.swing.JTextField a46;
    private javax.swing.JButton calculate_button;
    private javax.swing.JButton clean_button;
    private javax.swing.JLabel labe_w;
    private javax.swing.JLabel label_r;
    private javax.swing.JLabel label_v;
    private javax.swing.JLabel label_x;
    private javax.swing.JLabel label_y;
    private javax.swing.JLabel label_z;
    private javax.swing.JButton principal_button;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
