/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
import newtonmultivariable.NewtonMultivariableCalculator;

/**
 *
 * @author Yamil Elías
 */
public class GUINewtonMultivariableMethod extends javax.swing.JFrame {

    //Variables globales
    int grado1, grado2;
    double x, y;
    double[] funcion1, funcion2;

    NewtonMultivariableCalculator calculator;
    
    /**
     * Creates new form GUINewtonMultivariableMethod
     */
    public GUINewtonMultivariableMethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultScrollPane = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        controlPanel = new javax.swing.JPanel();
        calculateButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        valuesPanel = new javax.swing.JPanel();
        label_xvalue = new javax.swing.JLabel();
        label_yvalue = new javax.swing.JLabel();
        xValueTextField = new javax.swing.JTextField();
        yValueTextField = new javax.swing.JTextField();
        firstFunctionPanel = new javax.swing.JPanel();
        label_function01 = new javax.swing.JLabel();
        label_grade01 = new javax.swing.JLabel();
        gradeScroller01 = new javax.swing.JComboBox<>();
        x4Panel_01 = new javax.swing.JPanel();
        e_4 = new javax.swing.JLabel();
        x_l_4 = new javax.swing.JLabel();
        v_4 = new javax.swing.JTextField();
        x3Panel_01 = new javax.swing.JPanel();
        e_3 = new javax.swing.JLabel();
        x_l_3 = new javax.swing.JLabel();
        v_3 = new javax.swing.JTextField();
        x2Panel_01 = new javax.swing.JPanel();
        e_2 = new javax.swing.JLabel();
        x_l_2 = new javax.swing.JLabel();
        v_2 = new javax.swing.JTextField();
        x1Panel_01 = new javax.swing.JPanel();
        x_l_1 = new javax.swing.JLabel();
        v_1 = new javax.swing.JTextField();
        x0Panel_01 = new javax.swing.JPanel();
        v_0 = new javax.swing.JTextField();
        secondFunctionPanel = new javax.swing.JPanel();
        label_function02 = new javax.swing.JLabel();
        label_grade02 = new javax.swing.JLabel();
        gradeScroller02 = new javax.swing.JComboBox<>();
        x4Panel_02 = new javax.swing.JPanel();
        e_5 = new javax.swing.JLabel();
        x_l_5 = new javax.swing.JLabel();
        v_5 = new javax.swing.JTextField();
        x3Panel_02 = new javax.swing.JPanel();
        e_6 = new javax.swing.JLabel();
        x_l_6 = new javax.swing.JLabel();
        v_6 = new javax.swing.JTextField();
        x2Panel_02 = new javax.swing.JPanel();
        e_7 = new javax.swing.JLabel();
        x_l_7 = new javax.swing.JLabel();
        v_7 = new javax.swing.JTextField();
        x1Panel_02 = new javax.swing.JPanel();
        x_l_8 = new javax.swing.JLabel();
        v_8 = new javax.swing.JTextField();
        x0Panel_02 = new javax.swing.JPanel();
        v_9 = new javax.swing.JTextField();
        principalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultTextArea.setEditable(false);
        resultTextArea.setColumns(20);
        resultTextArea.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        resultTextArea.setForeground(new java.awt.Color(255, 255, 255));
        resultTextArea.setLineWrap(true);
        resultTextArea.setRows(5);
        resultTextArea.setToolTipText("Pantalla de resultados");
        resultTextArea.setOpaque(false);
        resultScrollPane.setViewportView(resultTextArea);

        controlPanel.setForeground(new java.awt.Color(255, 255, 255));

        calculateButton.setText("Calcular");
        calculateButton.setToolTipText("Toma los datos ingresados para calcular mediante Newton Raphson");
        calculateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        calculateButton.setBorderPainted(false);
        calculateButton.setOpaque(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Restablecer");
        resetButton.setToolTipText("Borra los datos para ingresar nuevos");
        resetButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        resetButton.setBorderPainted(false);
        resetButton.setEnabled(false);
        resetButton.setOpaque(false);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        valuesPanel.setForeground(new java.awt.Color(255, 255, 255));

        label_xvalue.setText("Valor de x: ");

        label_yvalue.setText("Valor de y: ");

        xValueTextField.setText("0");
        xValueTextField.setOpaque(false);
        xValueTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xValueTextFieldMouseClicked(evt);
            }
        });

        yValueTextField.setText("0");
        yValueTextField.setOpaque(false);
        yValueTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yValueTextFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout valuesPanelLayout = new javax.swing.GroupLayout(valuesPanel);
        valuesPanel.setLayout(valuesPanelLayout);
        valuesPanelLayout.setHorizontalGroup(
            valuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuesPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label_xvalue)
                .addGap(2, 2, 2)
                .addComponent(xValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(label_yvalue)
                .addGap(3, 3, 3)
                .addComponent(yValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        valuesPanelLayout.setVerticalGroup(
            valuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_xvalue)
                    .addComponent(label_yvalue)
                    .addComponent(xValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firstFunctionPanel.setForeground(new java.awt.Color(255, 255, 255));

        label_function01.setText("Primer polinomio");

        label_grade01.setText("Grado");

        gradeScroller01.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        gradeScroller01.setForeground(new java.awt.Color(255, 255, 255));
        gradeScroller01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5" }));
        gradeScroller01.setToolTipText("Selecciona el grado de la funcion");
        gradeScroller01.setFocusable(false);
        gradeScroller01.setOpaque(false);
        gradeScroller01.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradeScroller01ItemStateChanged(evt);
            }
        });

        x4Panel_01.setEnabled(false);

        e_4.setText("4");
        e_4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x_l_4.setText("x");
        x_l_4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_4.setText("0");
        v_4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_4.setOpaque(false);
        v_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x4Panel_01Layout = new javax.swing.GroupLayout(x4Panel_01);
        x4Panel_01.setLayout(x4Panel_01Layout);
        x4Panel_01Layout.setHorizontalGroup(
            x4Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x4Panel_01Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(x4Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(x4Panel_01Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(e_4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(x4Panel_01Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(x_l_4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        x4Panel_01Layout.setVerticalGroup(
            x4Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x4Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x4Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_4)))
            .addComponent(e_4)
        );

        x3Panel_01.setEnabled(false);

        e_3.setText("3");
        e_3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x_l_3.setText("x");
        x_l_3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_3.setText("0");
        v_3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_3.setOpaque(false);
        v_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x3Panel_01Layout = new javax.swing.GroupLayout(x3Panel_01);
        x3Panel_01.setLayout(x3Panel_01Layout);
        x3Panel_01Layout.setHorizontalGroup(
            x3Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3Panel_01Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(x3Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(x3Panel_01Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(e_3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(x3Panel_01Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(x_l_3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        x3Panel_01Layout.setVerticalGroup(
            x3Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x3Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_3)))
            .addComponent(e_3)
        );

        x2Panel_01.setEnabled(false);

        e_2.setText("2");
        e_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x_l_2.setText("x");
        x_l_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_2.setText("0");
        v_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_2.setOpaque(false);
        v_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x2Panel_01Layout = new javax.swing.GroupLayout(x2Panel_01);
        x2Panel_01.setLayout(x2Panel_01Layout);
        x2Panel_01Layout.setHorizontalGroup(
            x2Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2Panel_01Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(x2Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(x2Panel_01Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(e_2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(x2Panel_01Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(x_l_2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        x2Panel_01Layout.setVerticalGroup(
            x2Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x2Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_2)))
            .addComponent(e_2)
        );

        x1Panel_01.setEnabled(false);

        x_l_1.setText("x");
        x_l_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_1.setText("0");
        v_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_1.setOpaque(false);
        v_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x1Panel_01Layout = new javax.swing.GroupLayout(x1Panel_01);
        x1Panel_01.setLayout(x1Panel_01Layout);
        x1Panel_01Layout.setHorizontalGroup(
            x1Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1Panel_01Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(x_l_1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        x1Panel_01Layout.setVerticalGroup(
            x1Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x1Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_1)))
        );

        x0Panel_01.setEnabled(false);

        v_0.setText("0");
        v_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_0.setOpaque(false);
        v_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x0Panel_01Layout = new javax.swing.GroupLayout(x0Panel_01);
        x0Panel_01.setLayout(x0Panel_01Layout);
        x0Panel_01Layout.setHorizontalGroup(
            x0Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0Panel_01Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_0, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        x0Panel_01Layout.setVerticalGroup(
            x0Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout firstFunctionPanelLayout = new javax.swing.GroupLayout(firstFunctionPanel);
        firstFunctionPanel.setLayout(firstFunctionPanelLayout);
        firstFunctionPanelLayout.setHorizontalGroup(
            firstFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstFunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstFunctionPanelLayout.createSequentialGroup()
                        .addComponent(label_grade01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradeScroller01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_function01)
                    .addGroup(firstFunctionPanelLayout.createSequentialGroup()
                        .addComponent(x4Panel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x3Panel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x2Panel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x1Panel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x0Panel_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        firstFunctionPanelLayout.setVerticalGroup(
            firstFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstFunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_function01)
                .addGap(12, 12, 12)
                .addGroup(firstFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeScroller01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_grade01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(x4Panel_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x3Panel_01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x2Panel_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x1Panel_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x0Panel_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        secondFunctionPanel.setForeground(new java.awt.Color(255, 255, 255));

        label_function02.setText("Segundo polinomio");

        label_grade02.setText("Grado");

        gradeScroller02.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        gradeScroller02.setForeground(new java.awt.Color(255, 255, 255));
        gradeScroller02.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5" }));
        gradeScroller02.setToolTipText("Selecciona el grado de la funcion");
        gradeScroller02.setFocusable(false);
        gradeScroller02.setOpaque(false);
        gradeScroller02.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradeScroller02ItemStateChanged(evt);
            }
        });

        x4Panel_02.setEnabled(false);

        e_5.setText("4");
        e_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x_l_5.setText("x");
        x_l_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_5.setText("0");
        v_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_5.setOpaque(false);
        v_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x4Panel_02Layout = new javax.swing.GroupLayout(x4Panel_02);
        x4Panel_02.setLayout(x4Panel_02Layout);
        x4Panel_02Layout.setHorizontalGroup(
            x4Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x4Panel_02Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(x4Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(x4Panel_02Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(e_5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(x4Panel_02Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(x_l_5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        x4Panel_02Layout.setVerticalGroup(
            x4Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x4Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x4Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_5)))
            .addComponent(e_5)
        );

        x3Panel_02.setEnabled(false);

        e_6.setText("3");
        e_6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x_l_6.setText("x");
        x_l_6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_6.setText("0");
        v_6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_6.setOpaque(false);
        v_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x3Panel_02Layout = new javax.swing.GroupLayout(x3Panel_02);
        x3Panel_02.setLayout(x3Panel_02Layout);
        x3Panel_02Layout.setHorizontalGroup(
            x3Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3Panel_02Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(x3Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(x3Panel_02Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(e_6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(x3Panel_02Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(x_l_6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        x3Panel_02Layout.setVerticalGroup(
            x3Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x3Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_6)))
            .addComponent(e_6)
        );

        x2Panel_02.setEnabled(false);

        e_7.setText("2");
        e_7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x_l_7.setText("x");
        x_l_7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_7.setText("0");
        v_7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_7.setOpaque(false);
        v_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x2Panel_02Layout = new javax.swing.GroupLayout(x2Panel_02);
        x2Panel_02.setLayout(x2Panel_02Layout);
        x2Panel_02Layout.setHorizontalGroup(
            x2Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2Panel_02Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(x2Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(x2Panel_02Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(e_7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(x2Panel_02Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(x_l_7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        x2Panel_02Layout.setVerticalGroup(
            x2Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x2Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x2Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_7)))
            .addComponent(e_7)
        );

        x1Panel_02.setEnabled(false);

        x_l_8.setText("x");
        x_l_8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        v_8.setText("0");
        v_8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_8.setOpaque(false);
        v_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x1Panel_02Layout = new javax.swing.GroupLayout(x1Panel_02);
        x1Panel_02.setLayout(x1Panel_02Layout);
        x1Panel_02Layout.setHorizontalGroup(
            x1Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1Panel_02Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(x_l_8, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        x1Panel_02Layout.setVerticalGroup(
            x1Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x1Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(x1Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l_8)))
        );

        x0Panel_02.setEnabled(false);

        v_9.setText("0");
        v_9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        v_9.setOpaque(false);
        v_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x0Panel_02Layout = new javax.swing.GroupLayout(x0Panel_02);
        x0Panel_02.setLayout(x0Panel_02Layout);
        x0Panel_02Layout.setHorizontalGroup(
            x0Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0Panel_02Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(v_9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        x0Panel_02Layout.setVerticalGroup(
            x0Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x0Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout secondFunctionPanelLayout = new javax.swing.GroupLayout(secondFunctionPanel);
        secondFunctionPanel.setLayout(secondFunctionPanelLayout);
        secondFunctionPanelLayout.setHorizontalGroup(
            secondFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondFunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondFunctionPanelLayout.createSequentialGroup()
                        .addComponent(label_grade02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradeScroller02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_function02)
                    .addGroup(secondFunctionPanelLayout.createSequentialGroup()
                        .addComponent(x4Panel_02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x3Panel_02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x2Panel_02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x1Panel_02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x0Panel_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        secondFunctionPanelLayout.setVerticalGroup(
            secondFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondFunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_function02)
                .addGap(12, 12, 12)
                .addGroup(secondFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeScroller02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_grade02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(secondFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(x4Panel_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x3Panel_02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x2Panel_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x1Panel_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x0Panel_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        principalButton.setText("Principal");
        principalButton.setToolTipText("Volver al menú principal");
        principalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(valuesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstFunctionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(secondFunctionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(principalButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(principalButton)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstFunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondFunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultScrollPane)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:

        boolean validator=true; //Boolean para validación

        try {
            //Se define variables

            //Grados de funciones
            grado1 = Integer.parseInt((String) gradeScroller01.getSelectedItem());
            grado2 = Integer.parseInt((String) gradeScroller02.getSelectedItem());

            //Se crea la función en base al grado
            funcion1 = new double[grado1];
            funcion2 = new double[grado2];

            //Se asignan valores a 'x' y 'y'
            x = Double.parseDouble(xValueTextField.getText());
            y = Double.parseDouble(yValueTextField.getText());

            //Formar array de primer polinomio
            switch ((String) gradeScroller01.getSelectedItem()) {
                case "1":
                funcion1[0] = Double.parseDouble(v_0.getText());
                break;
                case "2":
                funcion1[1] = Double.parseDouble(v_0.getText());
                funcion1[0] = Double.parseDouble(v_1.getText());
                break;
                case "3":
                funcion1[2] = Double.parseDouble(v_0.getText());
                funcion1[1] = Double.parseDouble(v_1.getText());
                funcion1[0] = Double.parseDouble(v_2.getText());
                break;
                case "4":
                funcion1[3] = Double.parseDouble(v_0.getText());
                funcion1[2] = Double.parseDouble(v_1.getText());
                funcion1[1] = Double.parseDouble(v_2.getText());
                funcion1[0] = Double.parseDouble(v_3.getText());
                break;
                case "5":
                funcion1[4] = Double.parseDouble(v_0.getText());
                funcion1[3] = Double.parseDouble(v_1.getText());
                funcion1[2] = Double.parseDouble(v_2.getText());
                funcion1[1] = Double.parseDouble(v_3.getText());
                funcion1[0] = Double.parseDouble(v_4.getText());
                break;
                default:
                break;
            }

            //Formar array de segundo polinomio
            switch ((String) gradeScroller02.getSelectedItem()) {
                case "1":
                funcion2[0] = Double.parseDouble(v_9.getText());
                break;
                case "2":
                funcion2[1] = Double.parseDouble(v_9.getText());
                funcion2[0] = Double.parseDouble(v_8.getText());
                break;
                case "3":
                funcion2[2] = Double.parseDouble(v_9.getText());
                funcion2[1] = Double.parseDouble(v_8.getText());
                funcion2[0] = Double.parseDouble(v_7.getText());
                break;
                case "4":
                funcion2[3] = Double.parseDouble(v_9.getText());
                funcion2[2] = Double.parseDouble(v_8.getText());
                funcion2[1] = Double.parseDouble(v_7.getText());
                funcion2[0] = Double.parseDouble(v_6.getText());
                break;
                case "5":
                funcion2[4] = Double.parseDouble(v_9.getText());
                funcion2[3] = Double.parseDouble(v_8.getText());
                funcion2[2] = Double.parseDouble(v_7.getText());
                funcion2[1] = Double.parseDouble(v_6.getText());
                funcion2[0] = Double.parseDouble(v_5.getText());
                break;
                default:
                break;
            }
            
            calculator = new NewtonMultivariableCalculator(grado1, grado2, x, y, funcion1, funcion2);
        }
        catch (NumberFormatException | ArrayIndexOutOfBoundsException n)
        {
            JOptionPane.showMessageDialog(null, "Revisa bien los grados de los polinomios", "Advertencia", 2);
            validator = false; //Vuelve el boleano g a falso para que no pueda imprimir nada
        }
        finally //Validación
        {
            if(validator) //Si no hay error en los grados
            {
                if((Double.parseDouble(v_0.getText()) == 0)&&(Double.parseDouble(v_4.getText()) == 0)&&(Double.parseDouble(v_3.getText()) == 0)&&(Double.parseDouble(v_2.getText()) == 0)&&(Double.parseDouble(v_1.getText()) == 0))
                {
                    int jop1 = JOptionPane.showConfirmDialog(null, "Todos los valores del primer polinomio son 0. Si desea Continuar dar clic en Ok.", "Advertencia", 2);

                    if((Double.parseDouble(v_8.getText()) == 0)&&(Double.parseDouble(v_7.getText()) == 0)&&(Double.parseDouble(v_6.getText()) == 0)&&(Double.parseDouble(v_5.getText()) == 0)&&(Double.parseDouble(v_9.getText()) == 0))
                    {
                        int jop = JOptionPane.showConfirmDialog(null, "Todos los valores del segundo polinomio son 0. Si desea Continuar dar clic en Ok.", "Advertencia", 2);

                        if((jop==0)&&(jop1==0))
                        {
                            System.out.println("Entro para imprimir");
                            calculator.main();
                            resultTextArea.setText(calculator.getResult());
                            resetButton.setEnabled(true); // Activates reset button
                        }
                    }
                }
                else
                {
                    System.out.println("Entro para imprimir");
                    calculator.main();
                    System.out.println("Termino de calcular");
                    resultTextArea.setText(calculator.getResult());
                    System.out.println("Deberia de aparecer...");
                    resetButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:

        //Vuelve 0 todos los valores a 0
        v_0.setText("0");
        v_1.setText("0");
        v_2.setText("0");
        v_3.setText("0");
        v_4.setText("0");
        v_5.setText("0");
        v_6.setText("0");
        v_7.setText("0");
        v_8.setText("0");
        v_9.setText("0");
        xValueTextField.setText("0");
        yValueTextField.setText("0");

        //Vuelve los JComboBox a nada
        gradeScroller01.setSelectedIndex(0);
        gradeScroller02.setSelectedIndex(0);

    }//GEN-LAST:event_resetButtonActionPerformed

    private void xValueTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xValueTextFieldMouseClicked
        xValueTextField.setText("");
    }//GEN-LAST:event_xValueTextFieldMouseClicked

    private void yValueTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yValueTextFieldMouseClicked
        yValueTextField.setText("");
    }//GEN-LAST:event_yValueTextFieldMouseClicked

    private void gradeScroller01ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradeScroller01ItemStateChanged

        switch ((String)evt.getItem()) {
            case "1":
            if(evt.getStateChange()==1)
            {
                x0Panel_01.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_01.setVisible(false);
            }
            break;
            case "2":
            if(evt.getStateChange()==1)
            {
                x0Panel_01.setVisible(true);
                x1Panel_01.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_01.setVisible(false);
                x1Panel_01.setVisible(false);
            }
            break;
            case "3":
            if(evt.getStateChange()==1)
            {
                x0Panel_01.setVisible(true);
                x1Panel_01.setVisible(true);
                x2Panel_01.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_01.setVisible(false);
                x1Panel_01.setVisible(false);
                x2Panel_01.setVisible(false);
            }
            break;
            case "4":
            if(evt.getStateChange()==1)
            {
                x0Panel_01.setVisible(true);
                x1Panel_01.setVisible(true);
                x2Panel_01.setVisible(true);
                x3Panel_01.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_01.setVisible(false);
                x1Panel_01.setVisible(false);
                x2Panel_01.setVisible(false);
                x3Panel_01.setVisible(false);
            }
            break;
            case "5":
            if(evt.getStateChange()==1)
            {
                x0Panel_01.setVisible(true);
                x1Panel_01.setVisible(true);
                x2Panel_01.setVisible(true);
                x3Panel_01.setVisible(true);
                x4Panel_01.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_01.setVisible(false);
                x1Panel_01.setVisible(false);
                x2Panel_01.setVisible(false);
                x3Panel_01.setVisible(false);
                x4Panel_01.setVisible(false);
            }
            break;
            default:
            break;
        }
    }//GEN-LAST:event_gradeScroller01ItemStateChanged

    private void v_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_4MouseClicked
        // TODO add your handling code here:
        v_4.setText("");
    }//GEN-LAST:event_v_4MouseClicked

    private void v_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_3MouseClicked
        // TODO add your handling code here:
        v_3.setText("");
    }//GEN-LAST:event_v_3MouseClicked

    private void v_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_2MouseClicked
        // TODO add your handling code here:
        v_2.setText("");
    }//GEN-LAST:event_v_2MouseClicked

    private void v_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_1MouseClicked
        // TODO add your handling code here:
        v_1.setText("");
    }//GEN-LAST:event_v_1MouseClicked

    private void v_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_0MouseClicked
        // TODO add your handling code here:
        v_0.setText("");
    }//GEN-LAST:event_v_0MouseClicked

    private void gradeScroller02ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradeScroller02ItemStateChanged
        // TODO add your handling code here:

        switch ((String)evt.getItem()) {
            case "1":
            if(evt.getStateChange()==1)
            {
                x0Panel_02.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_02.setVisible(false);
            }
            break;
            case "2":
            if(evt.getStateChange()==1)
            {
                x0Panel_02.setVisible(true);
                x1Panel_02.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_02.setVisible(false);
                x1Panel_02.setVisible(false);
            }
            break;
            case "3":
            if(evt.getStateChange()==1)
            {
                x0Panel_02.setVisible(true);
                x1Panel_02.setVisible(true);
                x2Panel_02.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_02.setVisible(false);
                x1Panel_02.setVisible(false);
                x2Panel_02.setVisible(false);
            }
            break;
            case "4":
            if(evt.getStateChange()==1)
            {
                x0Panel_02.setVisible(true);
                x1Panel_02.setVisible(true);
                x2Panel_02.setVisible(true);
                x3Panel_02.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_02.setVisible(false);
                x1Panel_02.setVisible(false);
                x2Panel_02.setVisible(false);
                x3Panel_02.setVisible(false);
            }
            break;
            case "5":
            if(evt.getStateChange()==1)
            {
                x0Panel_02.setVisible(true);
                x1Panel_02.setVisible(true);
                x2Panel_02.setVisible(true);
                x3Panel_02.setVisible(true);
                x4Panel_02.setVisible(true);
            }
            else if(evt.getStateChange()==2)
            {
                x0Panel_02.setVisible(false);
                x1Panel_02.setVisible(false);
                x2Panel_02.setVisible(false);
                x3Panel_02.setVisible(false);
                x4Panel_02.setVisible(false);
            }
            break;
            default:
            break;
        }
    }//GEN-LAST:event_gradeScroller02ItemStateChanged

    private void v_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_5MouseClicked
        // TODO add your handling code here:
        v_5.setText("");
    }//GEN-LAST:event_v_5MouseClicked

    private void v_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_6MouseClicked
        // TODO add your handling code here:
        v_6.setText("");
    }//GEN-LAST:event_v_6MouseClicked

    private void v_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_7MouseClicked
        // TODO add your handling code here:
        v_7.setText("");
    }//GEN-LAST:event_v_7MouseClicked

    private void v_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_8MouseClicked
        // TODO add your handling code here:
        v_8.setText("");
    }//GEN-LAST:event_v_8MouseClicked

    private void v_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_9MouseClicked
        // TODO add your handling code here:
        v_9.setText("");
    }//GEN-LAST:event_v_9MouseClicked

    private void principalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalButtonActionPerformed
        GUI gui = new GUI();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_principalButtonActionPerformed

    public void hideElements(){
        x4Panel_01.setVisible(false);
        x3Panel_01.setVisible(false);
        x2Panel_01.setVisible(false);
        x1Panel_01.setVisible(false);
        x0Panel_01.setVisible(false);
        
        x4Panel_02.setVisible(false);
        x3Panel_02.setVisible(false);
        x2Panel_02.setVisible(false);
        x1Panel_02.setVisible(false);
        x0Panel_02.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel e_2;
    private javax.swing.JLabel e_3;
    private javax.swing.JLabel e_4;
    private javax.swing.JLabel e_5;
    private javax.swing.JLabel e_6;
    private javax.swing.JLabel e_7;
    private javax.swing.JPanel firstFunctionPanel;
    private javax.swing.JComboBox<String> gradeScroller01;
    private javax.swing.JComboBox<String> gradeScroller02;
    private javax.swing.JLabel label_function01;
    private javax.swing.JLabel label_function02;
    private javax.swing.JLabel label_grade01;
    private javax.swing.JLabel label_grade02;
    private javax.swing.JLabel label_xvalue;
    private javax.swing.JLabel label_yvalue;
    private javax.swing.JButton principalButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JPanel secondFunctionPanel;
    private javax.swing.JTextField v_0;
    private javax.swing.JTextField v_1;
    private javax.swing.JTextField v_2;
    private javax.swing.JTextField v_3;
    private javax.swing.JTextField v_4;
    private javax.swing.JTextField v_5;
    private javax.swing.JTextField v_6;
    private javax.swing.JTextField v_7;
    private javax.swing.JTextField v_8;
    private javax.swing.JTextField v_9;
    private javax.swing.JPanel valuesPanel;
    private javax.swing.JPanel x0Panel_01;
    private javax.swing.JPanel x0Panel_02;
    private javax.swing.JPanel x1Panel_01;
    private javax.swing.JPanel x1Panel_02;
    private javax.swing.JPanel x2Panel_01;
    private javax.swing.JPanel x2Panel_02;
    private javax.swing.JPanel x3Panel_01;
    private javax.swing.JPanel x3Panel_02;
    private javax.swing.JPanel x4Panel_01;
    private javax.swing.JPanel x4Panel_02;
    private javax.swing.JTextField xValueTextField;
    private javax.swing.JLabel x_l_1;
    private javax.swing.JLabel x_l_2;
    private javax.swing.JLabel x_l_3;
    private javax.swing.JLabel x_l_4;
    private javax.swing.JLabel x_l_5;
    private javax.swing.JLabel x_l_6;
    private javax.swing.JLabel x_l_7;
    private javax.swing.JLabel x_l_8;
    private javax.swing.JTextField yValueTextField;
    // End of variables declaration//GEN-END:variables
}
